[package]
name = "footprint-core"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "footprint_core"
path = "src/lib.rs"

[[bin]]
name = "footprint-core"
path = "src/main.rs"

[dependencies]
